### ISSUE TITLE
User Issue: Unable to gracefully terminate pods container

### ISSUE THREAD

**Issue by RB301** [DataDog/chaos-controller#666] opened 2023-02-22 00:51 UTC
**Describe the bug**
While executing a container-failure-graceful experiment I noticed that the injector pod starts, identifies the target pods but does not terminate the application container inside the pod.

**To Reproduce**
1. I applied the following "graceful container termination" Disruption :
<img width="420" alt="Screenshot 2023-02-21 at 16 43 21" src="https://user-images.githubusercontent.com/64221041/220485624-3ae95926-6336-4633-ab15-ca18876e2e17.png">

2. Delete the disruption once it's succeeded.

**Expected behavior**
I injected the disruption into a pod with 2 containers:

1. Application container (name: demo-curl)
2. Istio sidecar container (name: istio-proxy)

The expectation is for both the containers inside the pod to restart. The actual behavior observed is only the istio container restarts, the applications container in the pod does nothing.

**Screenshots**
we can see the injector pod spins up:
<img width="754" alt="Screenshot 2023-02-21 at 16 31 45" src="https://user-images.githubusercontent.com/64221041/220489990-0d1ecb6c-cccc-41f0-9290-ec099411a199.png">

It identifies the target pod:
<img width="499" alt="Screenshot 2023-02-22 at 12 22 31" src="https://user-images.githubusercontent.com/64221041/220622410-7d5b9938-6385-450d-bdda-cd85d31961fa.png">

The time stamp show that nothing has happened : 
<img width="667" alt="Screenshot 2023-02-21 at 16 21 23" src="https://user-images.githubusercontent.com/64221041/220490279-5bf2cfde-f68b-4b50-bc33-fd14ad48586a.png">

**Injector logs**

`{"level":"info","ts":1677068244553.9192,"caller":"injector/main.go:219","message":"injector targeting container","disruptionName":"container-failure-all-graceful","disruptionNamespace":"chaos-engineering-framework","targetName":"demo-curl-75585bc5dd-j7zhd","targetNodeName":"ip-0-xxx-xx","containerID":"docker://e8c649289fe1a8ec8547cadc487cb5cea5dd369f743d1b3f802bd7e3bda906b1","container name":"/k8s_curl_demo-curl-75585bc5dd-j7zhd_chaos-engineering-framework_ab0c72c0-b295-4c31-93e9-1790e7ac9dde_0"}
`

<img width="910" alt="Screenshot 2023-02-22 at 12 32 24" src="https://user-images.githubusercontent.com/64221041/220621763-06398c2c-b7de-46d6-b5e2-dad9a5f904b9.png">

**Application Logs**
This was checked, but showed no updates.

**Environment:**
Kubernetes version: 1.21
Controller version: 7.10.0
Cloud provider (or local): EKS
Base OS for Kubernetes: Amazon Linux (5.4.209-116.363.amzn2.x86_64)

**Comment by Devatoria** [comment] 2023-02-22 10:18
Hey, from what I understand of your use case here, it is the expected behavior of the container failure but I may be missing something, so let me know if it's the case.

The container failure is expected to SIGTERM (`forced: false`) or SIGKILL (`forced: true`) the container(s) in the targeted pod. Doing this will increase the restart count but the pod will NOT be recreated by Kubernetes. This behavior is related to kubelet itself which will keep the pod and recreate a new container into it instead of creating a new pod. Killing a container is different than killing a pod.

Is there something I'm missing that was unexpected here?

**Comment by RB301** [comment] 2023-02-22 12:03
To provide more context,  when we run a graceful failure, we expect the container to restart which we do not see happening.
We have two containers in this pod:

1.  Istio sidecar container
2. Application container

We can see the istio container restart, however we see the application container does not terminate. 
Application container logs show no indication to why the pod does not terminate.

_p.s will update the issue to provide this context._

**Comment by Devatoria** [comment] 2023-02-23 17:13
Is your application supposed to catch `SIGTERM` signals? I can reproduce your case locally with an application not expected to react to `SIGTERM` so the application just ignores it and nothing happens which is also expected. Note that this is exactly the kind of things we want to catch with that disruption, application not reacting to `SIGTERM` signals, since it is a potential issue with Kubernetes pods lifecycle. When a pod is terminated because of a rollout or an eviction for instance, kubelet will send a set of `SIGTERM` signals. After some time with no response to that signal from the application, usually 30s, kubelet will send a `SIGKILL` to force the application to shutdown.

The problems with this `SIGKILL` are that:
* the application can't catch it and can't gracefully terminate
* it slows down the rollout because it needs to wait for the 30s timeout

You can switch to `force: true` for the injector to send a `SIGKILL` instead which can't be trapped and which should kill all containers. If it is the case, then you just confirmed your application is ignoring `SIGTERM`. Can you keep us posted with that please? So we can validate that the problem is on the application side, not on the injector side.

**Comment by rimbesat** [comment] 2023-02-24 09:45
Thanks for your response Joris! So We have run a forced termination experiment which does kill all the containers correctly with the SIGKILL. Though, we have separately tried to send a SIGTERM signal with a` kill -15 <pid>` and a docker stop against our application which correctly shuts down the containers but its not catching it though the injector. Is it possible for the application to be able to catch only some SIGTERM signals?

**Comment by Devatoria** [comment] 2023-02-24 10:16
I would be surprised that the application ignores only some SIGTERM and not the others. Would you be able to verify that the PID to which the signal is sent by the injector is the expected one please? It is printed in the injector logs (log message is `injecting a container failure` and the field containing the PID is named `container`). It's a shot in the dark because if the SIGKILL is working I don't see why the SIGTERM would not.

If that's possible, could you also:
* `strace` your application to get received signals (to confirm the signal is received, even if ignored)
* print caught signals in your application (to confirm the signal is caught/trapped)

With those information we should at least be able to tell where the problem is. I'll do some similar testings against dummy apps on my side too.

**Comment by rimbesat** [comment] 2023-02-24 11:20
Thanks Joris, We will get back to you with this information

**Comment by Devatoria** [comment] 2023-02-28 11:53
I couldn't reproduce the problem locally so far. I applied the example we have on the local env we have (the one used to work on the chaos-controller project, lima) against the demo pod (also in examples). The `curl` container does not trap `SIGTERM` so nothing happens, which is expected, but I'm able to see the signal being received by the main process:

```
root@lima-default:~# strace -e 'trace=!all' -p 6211
strace: Process 6211 attached
[...]
--- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=0, si_uid=0} ---
```

PID `6211` is the PID returned by the container engine when inspecting the `curl` container, and also the one used by the injector. It is the main process of the container (defined as PID `1` within the container and its pid namespace) and the one receiving the SIGTERM/SIGKILL when stopping the container manually.

I ran the same test with the `SIGKILL` disruption just to be sure:

```
root@lima-default:~# strace -e 'trace=!all' -p 6211
strace: Process 6211 attached
[...]
+++ killed by SIGKILL +++
```

Let me know what you have on your side.

**Comment by rimbesat** [comment] 2023-03-02 10:54
Hi Joris! We appreciate your response, it was helpful for us in identifying our application was unable to receive signals since our ENTRYPOINT was defined in the "shell" form rather than the "exec" form. We have been able to validate the graceful termination experiment, and it correctly terminates. You may close this issue.

**Comment by Devatoria** [comment] 2023-03-02 13:25
Hi, glad to hear it helped you find the issue! I'm closing it now.

**Closed by Devatoria** 2023-03-02 13:25 UTC
