### ISSUE TITLE
Guidance running CPU pressure experiments

### ISSUE THREAD

**Issue by rimbesat** [DataDog/chaos-controller#706] opened 2023-04-20 14:21 UTC
**Describe the bug**
Hi DataDog Chaos Team! I am just moving this Discussion post to an issue for some more visibility

I just wanted to reach out to see if you better understand how to troubleshoot the issue we are having. We aren't able to see the effects of CPU pressure experiments and would like some guidance. We are running the controller on version 7.13.1

Our application pod fault-injection-showcase, consists of two containers, the application container fault-injection-showcase and an istio-proxy container

**To Reproduce**
Running a cpu pressure experiment on multiple containers using the following manifest.
apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: cpu-pressure-pod
  namespace: chaos-engineering-framework
spec:
  level: pod
  duration: 5m
  selector:
    app.kubernetes.io/name: "fault-injection-showcase"
    app: "fault-injection-showcase--plugin-master"
  count: 100%
  staticTargeting: true
  cpuPressure: 
    count: 100%
I find no evidence to suggest that the fault-injection-showcase container has increased cpu-pressure, only the istio-proxy container is showing 100% cpu pressure
The injector pod also reaches a Failed state after the duration. This only happens with the cpu-pressure experiments (not with state or network experiments)

status:
  phase: Failed
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-03-23T11:09:06Z'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2023-03-23T11:12:54Z'
      reason: PodFailed
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2023-03-23T11:12:54Z'
      reason: PodFailed
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-03-23T11:09:06Z'
  message: Pod was active on the node longer than the specified deadline
  reason: DeadlineExceeded
  hostIP: 
  startTime: '2023-03-23T11:09:06Z'
  containerStatuses:
    - name: injector
      state:
        terminated:
          exitCode: 137
          reason: Error
          startedAt: '2023-03-23T11:0

Im not sure if this failure is related/similar to this old issue that is now resolved https://github.com/DataDog/chaos-controller/issues/491 
However, if I specify the container in the manifest below

apiVersion: chaos.datadoghq.com/v1beta1
kind: Disruption
metadata:
  name: cpu-pressure-pod
  namespace: chaos-engineering-framework
spec:
  level: pod
  duration: 5m
  selector:
    app.kubernetes.io/name: "fault-injection-showcase"
    app: "fault-injection-showcase--plugin-master"
  containers: 
    - "fault-injection-showcase"
  count: 100%
  staticTargeting: true
  cpuPressure: 
    count: 100%
It correctly injects into the fault-injection-showcase container 100% cpu-pressure. Though the pod still fails.
I also ran one experiment where I specify both containers in the manifest istio-proxy and fault-injection-showcase
And I find that it targets all the necessary pods, but in one pod it injects the fault-injection-showcase containers (and not istio-proxy) and in the other pod it injects the istio-proxy (and not the fault-injection-showcase)

**Expected behavior**
The metrics to show 

**Screenshots**
istio proxy being injected (first picture) but not fault-injection-showcase (Second picture)
![image](https://user-images.githubusercontent.com/93604675/233385163-530cc28d-1cf9-4134-85d8-cae88e98ff34.png)

![image](https://user-images.githubusercontent.com/93604675/233385776-d3efe9dd-7d5a-48af-93d7-5779ede02ae3.png)

**Environment:**
 - Kubernetes version: 1.23
 - Controller version: 7.13.1

If you have any ideas on where to go about solving this, it would be greatly appreciated!

**Comment by craig-seeman** [comment] 2023-04-20 14:32
That injector is a bit suspect, I see you potentially have an OOM in the pod, perhaps that could be why it crashes/fails? (Exit code 137)

```
- name: injector
state:
terminated:
exitCode: 137
reason: Error
startedAt: '2023-03-23T11:0
```

**Comment by luphaz** [comment] 2023-04-20 14:32
Hello 👋 

Indeed we identified couple of unexpected behaviour in the actual implementation of the cpu-pressure injector.

We are putting pressure on a single container, are never successfully ending (hence a failed state), and do not reinject on container restart, we are also potentially not stressing enough cores in some cases.

All of those and more are addressed by the following [PR](https://github.com/DataDog/chaos-controller/pull/704) soon to be opened for review.

**Comment by luphaz** [comment] 2023-04-20 14:50
> That injector is a bit suspect, I see you potentially have an OOM in the pod, perhaps that could be why it crashes/fails? (Exit code 137)
> 
> ```
> - name: injector
> state:
> terminated:
> exitCode: 137
> reason: Error
> startedAt: '2023-03-23T11:0
> ```

In this specific case, the exit code 137 is because an [external program](https://tencentcloud.com/document/product/457/35758#standard-linux-interruption-signals) interrupted our injector.

> Linux programs send an exit code when they are interrupted by external signals. The value of the exit code is the value of the interrupt signal plus 128. For example, the value of SIGKILL is 9, so the program exit code is 9 + 128 = 137

The container received a SIGKILL hence it's exit code is 137.

It will be fixed when the PR will be merged

**Comment by rimbesat** [comment] 2023-04-21 08:18
Thanks @craig-seeman and @luphaz !!

**Comment by luphaz** [comment] 2023-06-28 14:25
Hello 👋 

Since the release of https://github.com/DataDog/chaos-controller/releases/tag/7.18.0 all the problems discussed here have been solved.

Let us know if you encounter any new issue following those changes.

Have a beautiful day 🌈

**Closed by luphaz** 2023-06-28 14:25 UTC
